name: publish
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: build package
      shell: bash
      run: |
        python -m build
    - name: publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}